---
title: 'Blog Post 2: Factoring in Economic Forces'
author: John Kulow
date: '2024-09-15'
slug: blog-post-2-factoring-in-economic-forces
categories: []
tags: []
---



```{r setup, warning = FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, messages = FALSE, warnings = FALSE)
```

```{r, include=FALSE}
library(ggplot2)
library(maps)
library(tidyverse)
library(blogdown)
```

```{r, include=FALSE}
d_popvote <- read_csv("data/popvote_1948-2020.csv")
d_fred <- read_csv("data/fred_econ.csv")
d_bea <- read_csv("data/bea_econ.csv") |> 
  rename(year = "Year",
         quarter = "Quarter", 
         gdp = "Gross domestic product", 
         gnp = "Gross national product", 
         dpi = "Disposable personal income", 
         consumption = "Personal consumption expenditures", 
         goods = "Goods", 
         durables = "Durable goods", 
         nondurables = "Nondurable goods", 
         services = "Services", 
         pop = "Population (midperiod, thousands)")
```

```{r, include=FALSE}
## filtering to Q2 and merging
d_inc_econ <- d_popvote |> 
  filter(incumbent_party == TRUE) |> 
  select(year, pv, pv2p, winner) |> 
  left_join(d_fred |> filter(quarter == 2)) |> 
  left_join(d_bea |> filter(quarter == "Q2") |> select(year, dpi))

## creating data set without 2020 outlier
d_inc_econ_2 <- d_inc_econ |>
  filter(year != 2020)
```

```{r}
## With 2020
d_inc_econ |> 
  ggplot(aes(x = GDP_growth_quarterly, y = pv2p, label = year)) + 
  geom_text() + 
  geom_smooth(method = "lm", formula = y ~ x) +
  geom_hline(yintercept = 50, lty = 2) + 
  geom_vline(xintercept = 0.01, lty = 2) + 
  labs(x = "Second Quarter GDP Growth (%)", 
       y = "Incumbent Party's National Popular Vote Share", 
       title = "Y = 51.25 + 0.274 * X") + 
  theme_bw() + 
  theme(plot.title = element_text(size = 18))

## without 2020
d_inc_econ_2 |> 
  ggplot(aes(x = GDP_growth_quarterly, y = pv2p, label = year)) + 
  geom_text() + 
  geom_smooth(method = "lm", formula = y ~ x) +
  geom_hline(yintercept = 50, lty = 2) + 
  geom_vline(xintercept = 0.01, lty = 2) + 
  labs(x = "Second Quarter GDP Growth (%)", 
       y = "Incumbent Party's National Popular Vote Share", 
       title = "Y = 49.38 + 0.737 * X") + 
  theme_bw() + 
  theme(plot.title = element_text(size = 18))
```





```{r, include=FALSE}
## build_site(build_rmd=TRUE)
```




























