---
title: 'Blog Post 10: Post-2024 Election Reflection'
author: John Kulow
date: '2024-11-18'
slug: blog-post-10-post-2024-election-reflection
categories: []
tags: []
---

Slay

```{r setup, warning = FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, messages = FALSE, warning = FALSE)
```

```{r libraries, include=FALSE}
library(blogdown)
library(car)
library(caret)
library(curl)
library(CVXR)
library(foreign)
library(geofacet)
library(ggpubr)
library(ggthemes)
library(glmnet)
library(gridExtra)
library(haven)
library(janitor)
library(kableExtra)
library(knitr)
library(maps)
library(mgcv)
library(mgcViz)
library(mlr3)
library(patchwork)
library(randomForest)
library(ranger)
library(RColorBrewer)
library(readxl)
library(rstan)
library(scales)
library(sf)
library(shinystan)
library(sjPlot)
library(spData)
library(stargazer)
library(tidygeocoder)
library(tidyverse)
library(tigris)
library(tmap)
library(tmaptools)
library(viridis)
```





```{r, include=FALSE}
## build_site(build_rmd=TRUE)
```